import { defineTheme } from "../components/ui/theme";

/** Generated by Balsa UI. Edit this definition in your application. */
export const myDesignSystemTheme = defineTheme({
  "id": "my-design-system",
  "name": "My Design System",
  "extends": "glassmorphism",
  "options": {
    "shape": "rounded",
    "size": "balanced",
    "spacing": "airy",
    "border": "strong",
    "elevation": "soft"
  },
  "overrides": {
    "tokens": {
      "typography": {
        "titleFonts": [
          "Poppins",
          "sans-serif"
        ],
        "bodyFonts": [
          "Open Sans",
          "sans-serif"
        ],
        "controlFonts": [
          "Open Sans",
          "sans-serif"
        ]
      },
      "radius": {
        "control": 16,
        "surface": 28,
        "panel": 36,
        "badge": 9999,
        "toggle": 9999,
        "codeControl": 8
      },
      "shadow": {
        "sm": [
          {
            "x": 0,
            "y": 2,
            "blur": 4,
            "spread": 0,
            "color": {
              "role": "foreground",
              "opacity": 0.09
            }
          }
        ],
        "md": [
          {
            "x": 0,
            "y": 4,
            "blur": 8,
            "spread": 0,
            "color": {
              "role": "foreground",
              "opacity": 0.09
            }
          }
        ],
        "lg": [
          {
            "x": 0,
            "y": 6,
            "blur": 12,
            "spread": 0,
            "color": {
              "role": "foreground",
              "opacity": 0.09
            }
          }
        ],
        "detail": [
          {
            "x": 0,
            "y": 1,
            "blur": 2,
            "spread": 0,
            "color": {
              "role": "foreground",
              "opacity": 0.09
            }
          }
        ]
      }
    }
  }
});
